config-version: 0


menu:

  # 解决Geyser上的不完美, 也可以设为 3 | Solve the imperfection on Geyser, or set it to 3
  size: 6 # 2 ~ 6

  title:
    HOME: "%1%'s Homes"
    PUBLIC_HOME: 'Public Homes'
    WARP: 'Warps'

  theme-item:
    HOME: ORANGE_STAINED_GLASS_PANE
    PUBLIC_HOME: LIME_STAINED_GLASS_PANE
    WARP: CYAN_STAINED_GLASS_PANE

  item:
    default-item: STONE
    name: '[%1%](#00fb9a)'
    # 如果没有描述, 则不显示 | If there is no description, it should not be displayed
    description: '' # '&7ℹ %1%'
    description-var1-no: '' # 'N/A'
    # 我添加了一个单独的功能用于显示这些. 在 menu.pagination.INFO | to menu.pagination.INFO
    space: '' # ' '
    Left: '' # '[Left Click:](#00fb9a) [Teleport](gray)'
    Right: '' # '[Right Click:](#00fb9a) [Edit](gray)'
    Shift: '' # '[Shift Click:](#00fb9a) [Set icon](gray)'

  pagination:
    FIRST:
      title: '[⏪ View first page (\1\)](#00fb9a)'
      item: EGG

    PREVIOUS:
      title: '[◀ View previous page \(%prevpage%\)](#00fb9a)'
      item: ARROW

    NEXT:
      title: '[View next page \(%nextpage%\) ▶](#00fb9a)'
      item: SPECTRAL_ARROW

    LAST:
      title: '[View last page \(%pages%\) ⏩](#00fb9a)'
      item: EGG

    INFO:
      enable: true
      title: '§fOperating Instructions'
      message:
        A: '§7  - Left Click: Teleport'
        B: '§7  - Right Click: Edit'
        C: '§7  - Shift Click: Set icon'
      item: OAK_SIGN


edit-menu:
  title:
    HOME: 'Edit Home: %1%'
    WARP: 'Edit Warp: %1%'
  theme-item:
    HOME: LIME_STAINED_GLASS_PANE
    WARP: LIME_STAINED_GLASS_PANE

  button:
    BACK:
      item: ORANGE_STAINED_GLASS_PANE
      text: 'Back'

    Update-location:
      item: OAK_BOAT
      text: 'Update Location'

    Update-name:
      item: NAME_TAG
      text: 'Update Name'
      anvil-menu:
        title: 'Update Name: %1%'

    Update-description:
      item: WRITABLE_BOOK
      text: 'Update Description'
      anvil-menu:
        title: 'Update Description: %1%'

    INFO:
      name: 'Name: %1%'
      description: '%1%'
      world: 'World: %1%'
      server: 'Server: %1%'
      coordinate: 'Coordinate: %x% %y% %z%'

    Update-privacy:
      item: NETHER_STAR
      text: 'Update privacy'

    del:
      item: BARRIER
      text: 'Delete'
      text-2: 'Right Click'

chat:
  updated-icon: '[Successfully updated the icon for](#00fb9a) [%1%](#00fb9a bold)'




