config-version: 0


menu:

  size: 4 # 2 ~ 6

  title:
    HOME: "%1%'s Homes"
    PUBLIC_HOME: 'Public Homes'
    WARP: 'Warps'

  theme-item:
    HOME: ORANGE_STAINED_GLASS_PANE
    PUBLIC_HOME: LIME_STAINED_GLASS_PANE
    WARP: CYAN_STAINED_GLASS_PANE

  item:
    default-item: STONE
    name: '[%1%](#00fb9a)'
    description: '&7ℹ %1%'
    description-var1-no: 'N/A'
    space: ' '
    Left: '[Left Click:](#00fb9a) [Teleport](gray)'
    Right: '[Right Click:](#00fb9a) [Edit](gray)'
    Shift: '[Shift Click:](#00fb9a) [Set icon](gray)'

  pagination:
    FIRST:
      title: '[⏪ View first page (\1\)](#00fb9a)'
      item: EGG

    PREVIOUS:
      title: '[◀ View previous page \(%prevpage%\)](#00fb9a)'
      item: ARROW

    NEXT:
      title: '[View next page \(%nextpage%\) ▶](#00fb9a)'
      item: SPECTRAL_ARROW

    LAST:
      title: '[View last page \(%pages%\) ⏩](#00fb9a)'
      item: EGG

    INFO:
      enable: true
      title: 'Operating Instructions'
      # '§7Left Click: Teleport\nRight Click: Edit\nShift Click: Set icon'
      message:
        A: '§7Left Click: Teleport'
        B: '§7Right Click: Edit'
        C: '§7Shift Click: Set icon'
      item: OAK_SIGN


chat:
  updated-icon: '[Successfully updated the icon for](#00fb9a) [%1%](#00fb9a bold)'




