name: HuskHomesGUI
main: net.william278.huskhomes.gui.HuskHomesGui
version: '${version}'
description: 'Display HuskHomes homes and warps in a GUI'
api-version: 1.16
depend: [ 'HuskHomes' ]
author: 'William278'
website: 'https://william278.net/'

commands:
  huskhomesgui:
    description: 'View HuskHomesGUI plugin information & reload configs'
    usage: '/<command> <reload/about>'
    permission: 'huskhomesgui.command'

permissions:
  huskhomesgui.command:
    description: 'Allows access to the /huskhomesgui command'
    default: op